language: php

matrix:
  include:
    - php: 5.4
      env: SYMFONY_VERSION=2.1 deps=low
    - php: 5.4
      env: SYMFONY_VERSION=2.1
    - php: 5.5
      env: SYMFONY_VERSION=2.8
    - php: 5.6
      env: SYMFONY_VERSION=2.8
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: nightly
    - env: deps=dev
env:
  global:
    - deps=no

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;
    - if [ "$deps" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
install:
    - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; else composer update; fi;

before_script:
    - cp phpunit.xml.dist phpunit.xml

script:
    - ./vendor/bin/simple-phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

